# -*- coding: utf-8 -*-
"""EDA_Session_PL_Salary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DNydfk39HLUDbb-m4mHWFNCpKapUrCT
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

df=pd.read_csv('/content/team_salary.csv')

df.head()

df.tail()

df

df.info()

df.describe()

df.shape

df.isnull().sum()

df.nunique()

df.sort_values(by="team",ascending=True)

df.sort_values(by="players",ascending=True)

df.sort_values(by="weekly",ascending=True)

df.sort_values(by="annual",ascending=True)

df.select_dtypes(include='number').corr()

numeric_df = df.select_dtypes(include='number')
corr_matrix = numeric_df.corr()

sns.heatmap(corr_matrix, annot=True)
plt.rcParams['figure.figsize']=(10,7)
plt.show()

df.groupby('team').mean()

df.groupby('team').median()

df.groupby('team').mean().sort_values(by='players',ascending=True).head()

df.groupby('team').mean().sort_values(by='players',ascending=True).tail()

df.groupby('team').mean().sort_values(by='players',ascending=True)

df.groupby('team').mean().sort_values(by='weekly',ascending=True)
df

df.plot()

df.transpose()

df.columns

df.shape

df.boxplot(figsize=(20, 10))

df.select_dtypes(include='number')

df.select_dtypes(include='float')

